<a href="https://colab.research.google.com/github/gulabpatel/Graph_Neural_Network/blob/main/01.3%3A%20Data_Handling_and_TransformerConv_Graph_Prediction_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Code Help

Video walkthrough the code :
1. https://www.youtube.com/watch?v=nAEb1lOf_4o
2. https://www.youtube.com/watch?v=QLIkOtKS4os&t=1s
3. https://www.youtube.com/watch?v=CJ-KdKCeiYg
4. https://www.youtube.com/watch?v=ZyiW_ibeDGc

# Install required libraries

In [ ]:
!pip install mlflow

In [ ]:
!pip install arm-mango

In [ ]:
!pip install deepchem

In [4]:
import sys
import os
import requests
import subprocess
import shutil
from logging import getLogger, StreamHandler, INFO
 
 
logger = getLogger(__name__)
logger.addHandler(StreamHandler())
logger.setLevel(INFO)
 
 
def install(
        chunk_size=4096,
        file_name="Miniconda3-latest-Linux-x86_64.sh",
        url_base="https://repo.continuum.io/miniconda/",
        conda_path=os.path.expanduser(os.path.join("~", "miniconda")),
        rdkit_version=None,
        add_python_path=True,
        force=False):
    """install rdkit from miniconda
    ```
    import rdkit_installer
    rdkit_installer.install()
    ```
    """
 
    python_path = os.path.join(
        conda_path,
        "lib",
        "python{0}.{1}".format(*sys.version_info),
        "site-packages",
    )
 
    if add_python_path and python_path not in sys.path:
        logger.info("add {} to PYTHONPATH".format(python_path))
        sys.path.append(python_path)
 
    if os.path.isdir(os.path.join(python_path, "rdkit")):
        logger.info("rdkit is already installed")
        if not force:
            return
 
        logger.info("force re-install")
 
    url = url_base + file_name
    python_version = "{0}.{1}.{2}".format(*sys.version_info)
 
    logger.info("python version: {}".format(python_version))
 
    if os.path.isdir(conda_path):
        logger.warning("remove current miniconda")
        shutil.rmtree(conda_path)
    elif os.path.isfile(conda_path):
        logger.warning("remove {}".format(conda_path))
        os.remove(conda_path)
 
    logger.info('fetching installer from {}'.format(url))
    res = requests.get(url, stream=True)
    res.raise_for_status()
    with open(file_name, 'wb') as f:
        for chunk in res.iter_content(chunk_size):
            f.write(chunk)
    logger.info('done')
 
    logger.info('installing miniconda to {}'.format(conda_path))
    subprocess.check_call(["bash", file_name, "-b", "-p", conda_path])
    logger.info('done')
 
    logger.info("installing rdkit")
    subprocess.check_call([
        os.path.join(conda_path, "bin", "conda"),
        "install",
        "--yes",
        "-c", "rdkit",
        "python==3.7.3",
        "rdkit" if rdkit_version is None else "rdkit=={}".format(rdkit_version)])
    logger.info("done")
 
    import rdkit
    logger.info("rdkit-{} installation finished!".format(rdkit.__version__))
 
 
if __name__ == "__main__":
    install()

add /root/miniconda/lib/python3.7/site-packages to PYTHONPATH
python version: 3.7.11
fetching installer from https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
done
installing miniconda to /root/miniconda
done
installing rdkit
done
rdkit-2020.09.1 installation finished!


In [5]:
# !pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/$pytorch_version
# !pip install --no-index torch-sparse -f https://pytorch-geometric.com/whl/$pytorch_version
# !pip install --no-index torch-cluster -f https://pytorch-geometric.com/whl/$pytorch_version
# !pip install --no-index torch-spline-conv -f https://pytorch-geometric.com/whl/$pytorch_version
# !pip install torch-geometric

!pip install -q torch-scatter -f https://pytorch-geometric.com/whl/torch-1.9.0+cu102.html
!pip install -q torch-sparse -f https://pytorch-geometric.com/whl/torch-1.9.0+cu102.html
!pip install -q torch-geometric

     |████████████████████████████████| 3.0 MB 6.9 MB/s 
     |████████████████████████████████| 1.6 MB 6.7 MB/s 
     |████████████████████████████████| 222 kB 7.1 MB/s 
     |████████████████████████████████| 376 kB 11.5 MB/s 
     |████████████████████████████████| 45 kB 4.7 MB/s 


#Import Libraries

In [6]:
import pandas as pd
import numpy as np 
from rdkit import Chem
import torch
import torch.nn.functional as F 
from torch.nn import Linear, BatchNorm1d, ModuleList
import torch_geometric
from torch_geometric.data import Dataset, Data
from torch_geometric.nn import TransformerConv, TopKPooling 
from torch_geometric.nn import global_mean_pool as gap, global_max_pool as gmp
from torch_geometric.data import DataLoader
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score, precision_score, recall_score, roc_auc_score
import mlflow.pytorch
import matplotlib.pyplot as plt 
import seaborn as sns
import os
from tqdm import tqdm
torch.manual_seed(42)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(f"Torch version: {torch.__version__}")
print(f"Cuda available: {torch.cuda.is_available()}")
print(f"Torch geometric version: {torch_geometric.__version__}")

Torch version: 1.9.0+cu102
Cuda available: False
Torch geometric version: 1.7.2


#Prepare Dataset

## Approach 1: Custome features

In [7]:
class MoleculeDataset(Dataset):
    def __init__(self, root, filename, test=False, transform=None, pre_transform=None):
        """
        root = Where the dataset should be stored. This folder is split
        into raw_dir (downloaded dataset) and processed_dir (processed data). 
        """
        self.test = test
        self.filename = filename
        super(MoleculeDataset, self).__init__(root, transform, pre_transform)
        
    @property
    def raw_file_names(self):
        """ If this file exists in raw_dir, the download is not triggered.
            (The download func. is not implemented here)  
        """
        return self.filename

    @property
    def processed_file_names(self):
        """ If these files are found in raw_dir, processing is skipped"""
        self.data = pd.read_csv(self.raw_paths[0]).reset_index()

        if self.test:
            return [f'data_test_{i}.pt' for i in list(self.data.index)]
        else:
            return [f'data_{i}.pt' for i in list(self.data.index)]

    def download(self):
        pass

    def process(self):
        self.data = pd.read_csv(self.raw_paths[0])
        for index, mol in tqdm(self.data.iterrows(), total=self.data.shape[0]):
            mol_obj = Chem.MolFromSmiles(mol["smiles"])
            # Get node features
            node_feats = self._get_node_features(mol_obj)
            # Get edge features
            edge_feats = self._get_edge_features(mol_obj)
            # Get adjacency info
            edge_index = self._get_adjacency_info(mol_obj)
            # Get labels info
            label = self._get_labels(mol["HIV_active"])

            # Create data object
            data = Data(x=node_feats, 
                        edge_index=edge_index,
                        edge_attr=edge_feats,
                        y=label,
                        smiles=mol["smiles"]
                        ) 
            if self.test:
                torch.save(data, 
                    os.path.join(self.processed_dir, 
                                 f'data_test_{index}.pt'))
            else:
                torch.save(data, 
                    os.path.join(self.processed_dir, 
                                 f'data_{index}.pt'))

    def _get_node_features(self, mol):
        """ 
        This will return a matrix / 2d array of the shape
        [Number of Nodes, Node Feature size]
        """
        all_node_feats = []

        for atom in mol.GetAtoms():
            node_feats = []
            # Feature 1: Atomic number        
            node_feats.append(atom.GetAtomicNum())
            # Feature 2: Atom degree
            node_feats.append(atom.GetDegree())
            # Feature 3: Formal charge
            node_feats.append(atom.GetFormalCharge())
            # Feature 4: Hybridization
            node_feats.append(atom.GetHybridization())
            # Feature 5: Aromaticity
            node_feats.append(atom.GetIsAromatic())
            # Feature 6: Total Num Hs
            node_feats.append(atom.GetTotalNumHs())
            # Feature 7: Radical Electrons
            node_feats.append(atom.GetNumRadicalElectrons())
            # Feature 8: In Ring
            node_feats.append(atom.IsInRing())
            # Feature 9: Chirality
            node_feats.append(atom.GetChiralTag())

            # Append node features to matrix
            all_node_feats.append(node_feats)

        all_node_feats = np.asarray(all_node_feats)
        return torch.tensor(all_node_feats, dtype=torch.float)

    def _get_edge_features(self, mol):
        """ 
        This will return a matrix / 2d array of the shape
        [Number of edges, Edge Feature size]
        """
        all_edge_feats = []

        for bond in mol.GetBonds():
            edge_feats = []
            # Feature 1: Bond type (as double)
            edge_feats.append(bond.GetBondTypeAsDouble())
            # Feature 2: Rings
            edge_feats.append(bond.IsInRing())
            # Append node features to matrix (twice, per direction)
            all_edge_feats += [edge_feats, edge_feats]

        all_edge_feats = np.asarray(all_edge_feats)
        return torch.tensor(all_edge_feats, dtype=torch.float)

    def _get_adjacency_info(self, mol):
        """
        We could also use rdmolops.GetAdjacencyMatrix(mol)
        but we want to be sure that the order of the indices
        matches the order of the edge features
        """
        edge_indices = []
        for bond in mol.GetBonds():
            i = bond.GetBeginAtomIdx()
            j = bond.GetEndAtomIdx()
            edge_indices += [[i, j], [j, i]]

        edge_indices = torch.tensor(edge_indices)
        edge_indices = edge_indices.t().to(torch.long).view(2, -1)
        return edge_indices

    def _get_labels(self, label):
        label = np.asarray([label])
        return torch.tensor(label, dtype=torch.int64)

    def len(self):
        return self.data.shape[0]

    def get(self, idx):
        """ - Equivalent to __getitem__ in pytorch
            - Is not needed for PyG's InMemoryDataset
        """
        if self.test:
            data = torch.load(os.path.join(self.processed_dir, 
                                 f'data_test_{idx}.pt'))
        else:
            data = torch.load(os.path.join(self.processed_dir, 
                                 f'data_{idx}.pt'))   
        return data

## Approach 2: Featurizer Library

    import deepchem as dc

In [ ]:
import deepchem as dc
class MoleculeDataset(Dataset):
    def __init__(self, root, filename, test=False, transform=None, pre_transform=None):
        """
        root = Where the dataset should be stored. This folder is split
        into raw_dir (downloaded dataset) and processed_dir (processed data). 
        """
        self.test = test
        self.filename = filename
        super(MoleculeDataset, self).__init__(root, transform, pre_transform)
        
    @property
    def raw_file_names(self):
        """ If this file exists in raw_dir, the download is not triggered.
            (The download func. is not implemented here)  
        """
        return self.filename

    @property
    def processed_file_names(self):
        """ If these files are found in raw_dir, processing is skipped"""
        self.data = pd.read_csv(self.raw_paths[0]).reset_index()

        if self.test:
            return [f'data_test_{i}.pt' for i in list(self.data.index)]
        else:
            return [f'data_{i}.pt' for i in list(self.data.index)]
        

    def download(self):
        pass

    def process(self):
        self.data = pd.read_csv(self.raw_paths[0]).reset_index()
        featurizer = dc.feat.MolGraphConvFeaturizer(use_edges=True)
        for index, mol in tqdm(self.data.iterrows(), total=self.data.shape[0]):
            # Featurize molecule
            f = featurizer.featurize(mol["smiles"])
            data = f[0].to_pyg_graph()
            data.y = self._get_label(mol["HIV_active"])
            data.smiles = mol["smiles"]
            if self.test:
                torch.save(data, 
                    os.path.join(self.processed_dir, 
                                 f'data_test_{index}.pt'))
            else:
                torch.save(data, 
                    os.path.join(self.processed_dir, 
                                 f'data_{index}.pt'))
            

    def _get_label(self, label):
        label = np.asarray([label])
        return torch.tensor(label, dtype=torch.int64)

    def len(self):
        return self.data.shape[0]

    def get(self, idx):
        """ - Equivalent to __getitem__ in pytorch
            - Is not needed for PyG's InMemoryDataset
        """
        if self.test:
            data = torch.load(os.path.join(self.processed_dir, 
                                 f'data_test_{idx}.pt'))
        else:
            data = torch.load(os.path.join(self.processed_dir, 
                                 f'data_{idx}.pt'))        
        return data

## Oversampling

In [ ]:
# data = pd.read_csv("https://raw.githubusercontent.com/gulabpatel/Graph_Neural_Network/master/data/HIV_train.csv")
# data.index = data["index"]
# data["HIV_active"].value_counts()
# start_index = data.iloc[0]["index"]

# # %% Apply oversampling

# # Check how many additional samples we need
# neg_class = data["HIV_active"].value_counts()[0]
# pos_class = data["HIV_active"].value_counts()[1]
# multiplier = int(neg_class/pos_class) - 1

# # Replicate the dataset for the positive class
# replicated_pos = [data[data["HIV_active"] == 1]]*multiplier

# # Append replicated data
# data = data.append(replicated_pos,
#                     ignore_index=True)
# print(data.shape)

# # Shuffle dataset
# data = data.sample(frac=1).reset_index(drop=True)

# # Re-assign index (This is our ID later)
# index = range(start_index, start_index + data.shape[0])
# data.index = index
# data["index"] = data.index
# data.head()

# # %% Save
# data.to_csv("HIV_train_oversampled.csv")

(71634, 4)


#Build GNN Model

##Parameters

In [8]:
HYPERPARAMETERS = {
    "batch_size": [32, 128, 64],
    "learning_rate": [0.1, 0.05, 0.01, 0.001],
    "weight_decay": [0.0001, 0.00001, 0.001],
    "sgd_momentum": [0.9, 0.8, 0.5],
    "scheduler_gamma": [0.995, 0.9, 0.8, 0.5, 1],
    "pos_weight" : [1.0, 1.3, 0.8, 0.9],  
    "model_embedding_size": [8, 16, 32, 64, 128],
    "model_attention_heads": [1, 2, 3, 4],
    "model_layers": [2, 4, 5, 8, 10],
    "model_dropout_rate": [0.2, 0.5, 0.9],
    "model_top_k_ratio": [0.2, 0.5, 0.8, 0.9],
    "model_top_k_every_n": [1, 2, 3],
    "model_dense_neurons": [128, 64, 256, 32]
}

BEST_PARAMETERS = {
    "batch_size": [128],
    "learning_rate": [0.01],
    "weight_decay": [0.0001],
    "sgd_momentum": [0.8],
    "scheduler_gamma": [0.8],
    "pos_weight": [1.3],
    "model_embedding_size": [64],
    "model_attention_heads": [3],
    "model_layers": [4],
    "model_dropout_rate": [0.2],
    "model_top_k_ratio": [0.5],
    "model_top_k_every_n": [1],
    "model_dense_neurons": [256]
}

## GNN Model

In [9]:
class GNN(torch.nn.Module):
    def __init__(self, feature_size, model_params):
        super(GNN, self).__init__()
        embedding_size = model_params["model_embedding_size"]
        n_heads = model_params["model_attention_heads"]
        self.n_layers = model_params["model_layers"]
        dropout_rate = model_params["model_dropout_rate"]
        top_k_ratio = model_params["model_top_k_ratio"]
        self.top_k_every_n = model_params["model_top_k_every_n"]
        dense_neurons = model_params["model_dense_neurons"]
        edge_dim = model_params["model_edge_dim"]

        self.conv_layers = ModuleList([])
        self.transf_layers = ModuleList([])
        self.pooling_layers = ModuleList([])
        self.bn_layers = ModuleList([])

        # Transformation layer
        self.conv1 = TransformerConv(feature_size, 
                                    embedding_size, 
                                    heads=n_heads, 
                                    dropout=dropout_rate,
                                    edge_dim=edge_dim,
                                    beta=True) 

        self.transf1 = Linear(embedding_size*n_heads, embedding_size)
        self.bn1 = BatchNorm1d(embedding_size)

        # Other layers
        for i in range(self.n_layers):
            self.conv_layers.append(TransformerConv(embedding_size, 
                                                    embedding_size, 
                                                    heads=n_heads, 
                                                    dropout=dropout_rate,
                                                    edge_dim=edge_dim,
                                                    beta=True))

            self.transf_layers.append(Linear(embedding_size*n_heads, embedding_size))
            self.bn_layers.append(BatchNorm1d(embedding_size))
            if i % self.top_k_every_n == 0:
                self.pooling_layers.append(TopKPooling(embedding_size, ratio=top_k_ratio))
            

        # Linear layers
        self.linear1 = Linear(embedding_size*2, dense_neurons)
        self.linear2 = Linear(dense_neurons, int(dense_neurons/2))  
        self.linear3 = Linear(int(dense_neurons/2), 1)  

    def forward(self, x, edge_attr, edge_index, batch_index):
        # Initial transformation
        x = self.conv1(x, edge_index, edge_attr)
        x = torch.relu(self.transf1(x))
        x = self.bn1(x)

        # Holds the intermediate graph representations
        global_representation = []

        for i in range(self.n_layers):
            x = self.conv_layers[i](x, edge_index, edge_attr)
            x = torch.relu(self.transf_layers[i](x))
            x = self.bn_layers[i](x)
            # Always aggregate last layer
            if i % self.top_k_every_n == 0 or i == self.n_layers:
                x , edge_index, edge_attr, batch_index, _, _ = self.pooling_layers[int(i/self.top_k_every_n)](
                    x, edge_index, edge_attr, batch_index
                    )
                # Add current representation
                global_representation.append(torch.cat([gmp(x, batch_index), gap(x, batch_index)], dim=1))
    
        x = sum(global_representation)

        # Output block
        x = torch.relu(self.linear1(x))
        x = F.dropout(x, p=0.8, training=self.training)
        x = torch.relu(self.linear2(x))
        x = F.dropout(x, p=0.8, training=self.training)
        x = self.linear3(x)

        return x

#Train Model

In [10]:
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

In [12]:
def train_one_epoch(epoch, model, train_loader, optimizer, loss_fn):
    # Enumerate over the data
    all_preds = []
    all_labels = []
    running_loss = 0.0
    step = 0
    for _, batch in enumerate(tqdm(train_loader)):
        # Use GPU
        batch.to(device)  
        # Reset gradients
        optimizer.zero_grad() 
        # Passing the node features and the connection info
        pred = model(batch.x.float(), 
                                batch.edge_attr.float(),
                                batch.edge_index, 
                                batch.batch) 
        # Calculating the loss and gradients
        loss = loss_fn(torch.squeeze(pred), batch.y.float())
        loss.backward()  
        optimizer.step()  
        # Update tracking
        running_loss += loss.item()
        step += 1
        all_preds.append(np.rint(torch.sigmoid(pred).cpu().detach().numpy()))
        all_labels.append(batch.y.cpu().detach().numpy())
    all_preds = np.concatenate(all_preds).ravel()
    all_labels = np.concatenate(all_labels).ravel()
    calculate_metrics(all_preds, all_labels, epoch, "train")
    return running_loss/step

def test(epoch, model, test_loader, loss_fn):
    all_preds = []
    all_preds_raw = []
    all_labels = []
    running_loss = 0.0
    step = 0
    for batch in test_loader:
        batch.to(device)  
        pred = model(batch.x.float(), 
                        batch.edge_attr.float(),
                        batch.edge_index, 
                        batch.batch) 
        loss = loss_fn(torch.squeeze(pred), batch.y.float())

         # Update tracking
        running_loss += loss.item()
        step += 1
        all_preds.append(np.rint(torch.sigmoid(pred).cpu().detach().numpy()))
        all_preds_raw.append(torch.sigmoid(pred).cpu().detach().numpy())
        all_labels.append(batch.y.cpu().detach().numpy())
    
    all_preds = np.concatenate(all_preds).ravel()
    all_labels = np.concatenate(all_labels).ravel()
    print(all_preds_raw[0][:10])
    print(all_preds[:10])
    print(all_labels[:10])
    calculate_metrics(all_preds, all_labels, epoch, "test")
    log_conf_matrix(all_preds, all_labels, epoch)
    return running_loss/step

def log_conf_matrix(y_pred, y_true, epoch):
    # Log confusion matrix as image
    cm = confusion_matrix(y_pred, y_true)
    classes = ["0", "1"]
    df_cfm = pd.DataFrame(cm, index = classes, columns = classes)
    plt.figure(figsize = (10,7))
    cfm_plot = sns.heatmap(df_cfm, annot=True, cmap='Blues', fmt='g')
    cfm_plot.figure.savefig(f'/content/data/images/cm_{epoch}.png')
    mlflow.log_artifact(f"/content/data/images/cm_{epoch}.png")

def calculate_metrics(y_pred, y_true, epoch, type):
    print(f"\n Confusion matrix: \n {confusion_matrix(y_pred, y_true)}")
    print(f"F1 Score: {f1_score(y_pred, y_true)}")
    print(f"Accuracy: {accuracy_score(y_pred, y_true)}")
    prec = precision_score(y_pred, y_true)
    rec = recall_score(y_pred, y_true)
    print(f"Precision: {prec}")
    print(f"Recall: {rec}")
    mlflow.log_metric(key=f"Precision-{type}", value=float(prec), step=epoch)
    mlflow.log_metric(key=f"Recall-{type}", value=float(rec), step=epoch)
    try:
        roc = roc_auc_score(y_pred, y_true)
        print(f"ROC AUC: {roc}")
        mlflow.log_metric(key=f"ROC-AUC-{type}", value=float(roc), step=epoch)
    except:
        mlflow.log_metric(key=f"ROC-AUC-{type}", value=float(0), step=epoch)
        print(f"ROC AUC: notdefined")

# %% Run the training
from mango import scheduler, Tuner

def run_one_training(params):
    params = params[0]
    with mlflow.start_run() as run:
        # Log parameters used in this experiment
        for key in params.keys():
            mlflow.log_param(key, params[key])

        # Loading the dataset
        print("Loading dataset...")
        train_dataset = MoleculeDataset(root="/content/data/", filename="HIV_train_oversampled.csv")
        test_dataset = MoleculeDataset(root="/content/data/", filename="HIV_test.csv", test=True)
        params["model_edge_dim"] = train_dataset[0].edge_attr.shape[1]

        # Prepare training
        train_loader = DataLoader(train_dataset, batch_size=params["batch_size"], shuffle=True)
        test_loader = DataLoader(test_dataset, batch_size=params["batch_size"], shuffle=True)

        # Loading the model
        print("Loading model...")
        model_params = {k: v for k, v in params.items() if k.startswith("model_")}
        model = GNN(feature_size=train_dataset[0].x.shape[1], model_params=model_params) 
        model = model.to(device)
        print(f"Number of parameters: {count_parameters(model)}")
        mlflow.log_param("num_params", count_parameters(model))

        # < 1 increases precision, > 1 recall
        weight = torch.tensor([params["pos_weight"]], dtype=torch.float32).to(device)
        loss_fn = torch.nn.BCEWithLogitsLoss(pos_weight=weight)
        optimizer = torch.optim.SGD(model.parameters(), 
                                    lr=params["learning_rate"],
                                    momentum=params["sgd_momentum"],
                                    weight_decay=params["weight_decay"])
        scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=params["scheduler_gamma"])
        
        # Start training
        best_loss = 1000
        early_stopping_counter = 0
        for epoch in range(300): 
            if early_stopping_counter <= 10: # = x * 5 
                # Training
                model.train()
                loss = train_one_epoch(epoch, model, train_loader, optimizer, loss_fn)
                print(f"Epoch {epoch} | Train Loss {loss}")
                mlflow.log_metric(key="Train loss", value=float(loss), step=epoch)

                # Testing
                model.eval()
                if epoch % 5 == 0:
                    loss = test(epoch, model, test_loader, loss_fn)
                    print(f"Epoch {epoch} | Test Loss {loss}")
                    mlflow.log_metric(key="Test loss", value=float(loss), step=epoch)
                    
                    # Update best loss
                    if float(loss) < best_loss:
                        best_loss = loss
                        # Save the currently best model 
                        mlflow.pytorch.log_model(model, "model")
                        early_stopping_counter = 0
                    else:
                        early_stopping_counter += 1

                scheduler.step()
            else:
                print("Early stopping due to no improvement.")
                return [best_loss]
    print(f"Finishing training with best test loss: {best_loss}")
    return [best_loss]



# Hyperparameter search

In [ ]:
# Hyperparameter search
print("Running hyperparameter search...")
config = dict()
config["optimizer"] = "Bayesian"
config["num_iteration"] = 100

tuner = Tuner(HYPERPARAMETERS, 
              objective=run_one_training,
              conf_dict=config) 
results = tuner.minimize()

Running hyperparameter search...
Loading dataset...


  0%|          | 18/71634 [00:00<06:42, 177.82it/s]

Processing...


  1%|          | 46/3999 [00:00<00:08, 452.53it/s]

Done!
Processing...


  0%|          | 0/1120 [00:00<?, ?it/s]

Done!
Loading model...
Number of parameters: 107393


100%|██████████| 1120/1120 [01:45<00:00, 10.57it/s]



 Confusion matrix: 
 [[21783 20998]
 [14067 14786]]
F1 Score: 0.45750885715611805
Accuracy: 0.5104978083033197
Precision: 0.4132014308070646
Recall: 0.5124597095622639
ROC AUC: 0.5108171715806458
Epoch 0 | Train Loss 0.7193575033651931
[[0.4848217]
 [0.4848217]
 [0.4848217]
 [0.4848217]
 [0.4848217]
 [0.4848217]
 [0.4848217]
 [0.4848217]
 [0.4848217]
 [0.4848217]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 1 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3834  165]
 [   0    0]]
F1 Score: 0.0
Accuracy: 0.9587396849212303
Precision: 0.0
Recall: 0.0
ROC AUC: notdefined
Epoch 0 | Test Loss 0.6657595511466737


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[21225 20333]
 [14625 15451]]
F1 Score: 0.4692074096568479
Accuracy: 0.5119915124103079
Precision: 0.4317851553767047
Recall: 0.5137318792392606
ROC AUC: 0.5122319341333219
Epoch 1 | Train Loss 0.6932941076478788


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[25645 24029]
 [10205 11755]]
F1 Score: 0.4071418675533388
Accuracy: 0.5220984448725465
Precision: 0.32849877040017883
Recall: 0.5352914389799636
ROC AUC: 0.5257787468282271
Epoch 2 | Train Loss 0.6907515985092947


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29868 27402]
 [ 5982  8382]]
F1 Score: 0.33429050011964584
Accuracy: 0.5339643186196499
Precision: 0.23423876592890677
Recall: 0.5835421888053467
ROC AUC: 0.552535892726403
Epoch 3 | Train Loss 0.6881342451487269


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[30637 27032]
 [ 5213  8752]]
F1 Score: 0.35184626826669885
Accuracy: 0.5498645894407683
Precision: 0.2445785826067516
Recall: 0.6267096312209094
ROC AUC: 0.5789827959811911
Epoch 4 | Train Loss 0.6847330038568803


100%|██████████| 1120/1120 [01:32<00:00, 12.08it/s]



 Confusion matrix: 
 [[31304 27179]
 [ 4546  8605]]
F1 Score: 0.35169101869827324
Accuracy: 0.5571237122037022
Precision: 0.24047060138609436
Recall: 0.6543228651813551
ROC AUC: 0.5947947619342475
Epoch 5 | Train Loss 0.6818184408758368
[[0.473637]
 [0.473637]
 [0.473637]
 [0.473637]
 [0.473637]
 [0.473637]
 [0.473637]
 [0.473637]
 [0.473637]
 [0.473637]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3834  165]
 [   0    0]]
F1 Score: 0.0
Accuracy: 0.9587396849212303
Precision: 0.0
Recall: 0.0
ROC AUC: notdefined
Epoch 5 | Test Loss 0.6461113975161598


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[30892 26487]
 [ 4958  9297]]
F1 Score: 0.3715901596754531
Accuracy: 0.5610324706145127
Precision: 0.25980885311871227
Recall: 0.6521922132585057
ROC AUC: 0.595288668367868
Epoch 6 | Train Loss 0.6789358463670526


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[31220 26608]
 [ 4630  9176]]
F1 Score: 0.37007461181689855
Accuracy: 0.563922159868219
Precision: 0.2564274536105522
Recall: 0.6646385629436476
ROC AUC: 0.6022577195986829
Epoch 7 | Train Loss 0.6779471314379147


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[30867 26306]
 [ 4983  9478]]
F1 Score: 0.37727137028560054
Accuracy: 0.5632102074433928
Precision: 0.26486697965571204
Recall: 0.6554180208837563
ROC AUC: 0.5976528650585679
Epoch 8 | Train Loss 0.6772041521434273


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[30997 26325]
 [ 4853  9459]]
F1 Score: 0.3776349409134462
Accuracy: 0.5647597509562499
Precision: 0.2643360160965795
Recall: 0.6609139183901621
ROC AUC: 0.6008330800561814
Epoch 9 | Train Loss 0.6762493279363427


100%|██████████| 1120/1120 [01:29<00:00, 12.45it/s]



 Confusion matrix: 
 [[31009 26162]
 [ 4841  9622]]
F1 Score: 0.3829880390869107
Accuracy: 0.5672027249630064
Precision: 0.26889112452492736
Recall: 0.6652838276982646
ROC AUC: 0.6038371002198447
Epoch 10 | Train Loss 0.6751596766923155
[[0.472838]
 [0.472838]
 [0.472838]
 [0.472838]
 [0.472838]
 [0.472838]
 [0.472838]
 [0.472838]
 [0.472838]
 [0.472838]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3834  165]
 [   0    0]]
F1 Score: 0.0
Accuracy: 0.9587396849212303
Precision: 0.0
Recall: 0.0
ROC AUC: notdefined
Epoch 10 | Test Loss 0.6446978970179482


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[30850 26127]
 [ 5000  9657]]
F1 Score: 0.3829027973275708
Accuracy: 0.565471703381076
Precision: 0.2698692152917505
Recall: 0.6588660708194037
ROC AUC: 0.6001563097133683
Epoch 11 | Train Loss 0.6751498057906117


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[30399 25549]
 [ 5451 10235]]
F1 Score: 0.39770740237031277
Accuracy: 0.5672446045174079
Precision: 0.286021685669573
Recall: 0.6524926686217009
ROC AUC: 0.5979182439412214
Epoch 12 | Train Loss 0.673660561548812


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[30192 25269]
 [ 5658 10515]]
F1 Score: 0.40475778047231364
Accuracy: 0.5682636736745121
Precision: 0.29384641180415827
Recall: 0.6501576701910592
ROC AUC: 0.5972701046362879
Epoch 13 | Train Loss 0.6735506797475475


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[30031 25189]
 [ 5819 10595]]
F1 Score: 0.4059542511207326
Accuracy: 0.5671329257056705
Precision: 0.2960820478426112
Recall: 0.6454855611063726
ROC AUC: 0.5946641858411255
Epoch 14 | Train Loss 0.6737265724156584


100%|██████████| 1120/1120 [01:30<00:00, 12.38it/s]



 Confusion matrix: 
 [[29988 24995]
 [ 5862 10789]]
F1 Score: 0.4115190235529704
Accuracy: 0.5692408632772147
Precision: 0.3015034652358596
Recall: 0.6479490721278002
ROC AUC: 0.5966770077369628
Epoch 15 | Train Loss 0.6739416841417551


  0%|          | 0/1120 [00:00<?, ?it/s]

[[0.47819906]
 [0.47819906]
 [0.47819906]
 [0.47819906]
 [0.47819906]
 [0.47819906]
 [0.47819906]
 [0.47819906]
 [0.47819906]
 [0.47819906]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 1 0 0 0 0 0 0 0 1]

 Confusion matrix: 
 [[3834  165]
 [   0    0]]
F1 Score: 0.0
Accuracy: 0.9587396849212303
Precision: 0.0
Recall: 0.0
ROC AUC: notdefined
Epoch 15 | Test Loss 0.6541322271029154


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29633 24571]
 [ 6217 11213]]
F1 Score: 0.421430450633292
Accuracy: 0.5702040930284502
Precision: 0.3133523362396602
Recall: 0.6433161216293747
ROC AUC: 0.5950050462770149
Epoch 16 | Train Loss 0.674131447502545


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29698 24589]
 [ 6152 11195]]
F1 Score: 0.42141122884944754
Accuracy: 0.5708602060474076
Precision: 0.31284931813100825
Recall: 0.6453565458004266
ROC AUC: 0.596206005138134
Epoch 17 | Train Loss 0.6725170201488904


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29770 24786]
 [ 6080 10998]]
F1 Score: 0.416102304112595
Accuracy: 0.5691152246140101
Precision: 0.3073440643863179
Recall: 0.643986415271109
ROC AUC: 0.594832125444778
Epoch 18 | Train Loss 0.6730312713022742


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[30003 24920]
 [ 5847 10864]]
F1 Score: 0.4139060862939328
Accuracy: 0.570497249909261
Precision: 0.30359937402190923
Recall: 0.650110705523308
ROC AUC: 0.5981922899282327
Epoch 19 | Train Loss 0.6722513219607728


100%|██████████| 1120/1120 [01:28<00:00, 12.68it/s]



 Confusion matrix: 
 [[29992 24908]
 [ 5858 10876]]
F1 Score: 0.41418180433375223
Accuracy: 0.5705112097607281
Precision: 0.3039347194276772
Recall: 0.6499342655671089
ROC AUC: 0.5981183167544106
Epoch 20 | Train Loss 0.6718496401927301
[[0.47220322]
 [0.47220322]
 [0.47220322]
 [0.47220322]
 [0.47220322]
 [0.47220322]
 [0.47220322]
 [0.47220322]
 [0.47220322]
 [0.47220322]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1 1 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3833  164]
 [   1    1]]
F1 Score: 0.011976047904191616
Accuracy: 0.9587396849212303
Precision: 0.006060606060606061
Recall: 0.5
ROC AUC: 0.7294846134600952


  0%|          | 0/1120 [00:00<?, ?it/s]

Epoch 20 | Test Loss 0.6436145892218937


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29910 24792]
 [ 5940 10992]]
F1 Score: 0.4170270885499658
Accuracy: 0.5709858447106123
Precision: 0.3071763916834339
Recall: 0.6491849751948973
ROC AUC: 0.5979828572365843
Epoch 21 | Train Loss 0.6719448657440288


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29960 24827]
 [ 5890 10957]]
F1 Score: 0.41637058007638084
Accuracy: 0.57119524248262
Precision: 0.30619830091661077
Recall: 0.6503828574820443
ROC AUC: 0.5986139559828861
Epoch 22 | Train Loss 0.6720612505184752


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29729 24593]
 [ 6121 11191]]
F1 Score: 0.4215383456380895
Accuracy: 0.5712371220370215
Precision: 0.31273753632908563
Recall: 0.6464302218114603
ROC AUC: 0.5968519431284024
Epoch 23 | Train Loss 0.6723657856562308


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29812 24755]
 [ 6038 11029]]
F1 Score: 0.4173620177480086
Accuracy: 0.5701342937711142
Precision: 0.3082103733512184
Recall: 0.6462178473076697
ROC AUC: 0.5962776886583248
Epoch 24 | Train Loss 0.6719877577785934


100%|██████████| 1120/1120 [01:30<00:00, 12.38it/s]



 Confusion matrix: 
 [[29905 24774]
 [ 5945 11010]]
F1 Score: 0.4175278257077305
Accuracy: 0.5711673227796856
Precision: 0.30767940979208586
Recall: 0.6493659687407844
ROC AUC: 0.5981426306697027
Epoch 25 | Train Loss 0.6725003682609115
[[0.4683882 ]
 [0.46903047]
 [0.46793297]
 [0.48098552]
 [0.47405916]
 [0.46759295]
 [0.46528715]
 [0.4683246 ]
 [0.4685504 ]
 [0.46848217]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3832  164]
 [   2    1]]
F1 Score: 0.011904761904761906
Accuracy: 0.9584896224056014
Precision: 0.006060606060606061
Recall: 0.3333333333333333
ROC AUC: 0.6461461461461462


  0%|          | 0/1120 [00:00<?, ?it/s]

Epoch 25 | Test Loss 0.6389039754867554


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29777 24616]
 [ 6073 11168]]
F1 Score: 0.4212352663837812
Accuracy: 0.571586118323701
Precision: 0.3120947909680304
Recall: 0.647758250681515
ROC AUC: 0.5976000085426401
Epoch 26 | Train Loss 0.6716503135859966


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29777 24654]
 [ 6073 11130]]
F1 Score: 0.420103044142903
Accuracy: 0.5710556439679482
Precision: 0.31103286384976525
Recall: 0.6469801778759519
ROC AUC: 0.5970198789473455
Epoch 27 | Train Loss 0.6711692728634392


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29791 24759]
 [ 6059 11025]]
F1 Score: 0.41707649239615646
Accuracy: 0.5697852974844347
Precision: 0.30809859154929575
Recall: 0.6453406696324046
ROC AUC: 0.5957317463652398
Epoch 28 | Train Loss 0.6725003506988287


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29835 24724]
 [ 6015 11060]]
F1 Score: 0.4184717834238257
Accuracy: 0.570888125750342
Precision: 0.30907668231611896
Recall: 0.6477306002928258
ROC AUC: 0.5972849009455478
Epoch 29 | Train Loss 0.6719061224056142


100%|██████████| 1120/1120 [01:29<00:00, 12.47it/s]



 Confusion matrix: 
 [[29911 24707]
 [ 5939 11077]]
F1 Score: 0.4195833333333333
Accuracy: 0.5721863919367898
Precision: 0.30955175497429016
Recall: 0.6509755524212506
ROC AUC: 0.5993077622957987
Epoch 30 | Train Loss 0.6711990811462913


  0%|          | 0/1120 [00:00<?, ?it/s]

[[0.47294205]
 [0.47294205]
 [0.47294205]
 [0.47294205]
 [0.47294205]
 [0.47294205]
 [0.47294205]
 [0.47294205]
 [0.47294205]
 [0.47294205]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3834  165]
 [   0    0]]
F1 Score: 0.0
Accuracy: 0.9587396849212303
Precision: 0.0
Recall: 0.0
ROC AUC: notdefined
Epoch 30 | Test Loss 0.6449354111202179


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29770 24666]
 [ 6080 11118]]
F1 Score: 0.4196897059378657
Accuracy: 0.5707904067900718
Precision: 0.31069751844399734
Recall: 0.646470519827887
ROC AUC: 0.5966756302570988
Epoch 31 | Train Loss 0.6718522188386746


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29863 24673]
 [ 5987 11111]]
F1 Score: 0.4202185999016679
Accuracy: 0.5719909540162492
Precision: 0.3105019002906327
Recall: 0.6498420867937771
ROC AUC: 0.5987126672783614
Epoch 32 | Train Loss 0.671368431566017


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29876 24790]
 [ 5974 10994]]
F1 Score: 0.41681831968456173
Accuracy: 0.5705391294636625
Precision: 0.3072322825843953
Recall: 0.6479255068363979
ROC AUC: 0.5972221834112477
Epoch 33 | Train Loss 0.6721609222569636


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29771 24657]
 [ 6079 11127]]
F1 Score: 0.41996603132666543
Accuracy: 0.5709300053047436
Precision: 0.31094902749832326
Recall: 0.6466930140648611
ROC AUC: 0.5968362549562933
Epoch 34 | Train Loss 0.672517712946449


100%|██████████| 1120/1120 [01:31<00:00, 12.29it/s]



 Confusion matrix: 
 [[29811 24788]
 [ 6039 10996]]
F1 Score: 0.41636532308449614
Accuracy: 0.5696596588212302
Precision: 0.3072881734853566
Recall: 0.6454945700029351
ROC AUC: 0.595746790486916
Epoch 35 | Train Loss 0.6722480654184307
[[0.46765247]
 [0.46648398]
 [0.4840832 ]
 [0.46885136]
 [0.46848541]
 [0.47215188]
 [0.4662457 ]
 [0.46821347]
 [0.46710292]
 [0.46753234]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 1 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3832  164]
 [   2    1]]
F1 Score: 0.011904761904761906
Accuracy: 0.9584896224056014
Precision: 0.006060606060606061
Recall: 0.3333333333333333
ROC AUC: 0.6461461461461462


  0%|          | 2/1120 [00:00<01:32, 12.12it/s]

Epoch 35 | Test Loss 0.6396568237789093


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29781 24744]
 [ 6069 11040]]
F1 Score: 0.41744654302081563
Accuracy: 0.5698550967417707
Precision: 0.3085177733065057
Recall: 0.6452744169735227
ROC AUC: 0.5957321190782332
Epoch 36 | Train Loss 0.6724205411438431


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29782 24591]
 [ 6068 11193]]
F1 Score: 0.4220190404373645
Accuracy: 0.5720049138677165
Precision: 0.31279342723004694
Recall: 0.6484560570071259
ROC AUC: 0.5980955730569258
Epoch 37 | Train Loss 0.6707878532686404


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29749 24619]
 [ 6101 11165]]
F1 Score: 0.42092365692742695
Accuracy: 0.5711533629282184
Precision: 0.3120109546165884
Recall: 0.6466465886713773
ROC AUC: 0.5969125380084372
Epoch 38 | Train Loss 0.6714823787233659


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29774 24691]
 [ 6076 11093]]
F1 Score: 0.4189753177345949
Accuracy: 0.570497249909261
Precision: 0.3099988821819808
Recall: 0.6461063544760907
ROC AUC: 0.5963846745298842
Epoch 39 | Train Loss 0.6720724322433983


100%|██████████| 1120/1120 [01:32<00:00, 12.05it/s]



 Confusion matrix: 
 [[29651 24699]
 [ 6199 11085]]
F1 Score: 0.41776588527926434
Accuracy: 0.5686685093670604
Precision: 0.3097753185781355
Recall: 0.6413445961582966
ROC AUC: 0.5934505869475936
Epoch 40 | Train Loss 0.67278720417193
[[0.47299105]
 [0.47299105]
 [0.47299105]
 [0.47299105]
 [0.47299105]
 [0.47299105]
 [0.47299105]
 [0.47299105]
 [0.47299105]
 [0.47299105]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3834  165]
 [   0    0]]
F1 Score: 0.0
Accuracy: 0.9587396849212303
Precision: 0.0
Recall: 0.0
ROC AUC: notdefined


  0%|          | 2/1120 [00:00<01:35, 11.73it/s]

Epoch 40 | Test Loss 0.6450160334980677


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29733 24793]
 [ 6117 10991]]
F1 Score: 0.4156016032670347
Accuracy: 0.5685009911494542
Precision: 0.3071484462329533
Recall: 0.6424479775543606
ROC AUC: 0.593873733852924
Epoch 41 | Train Loss 0.673213447577187


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29872 24656]
 [ 5978 11128]]
F1 Score: 0.42079788239742866
Accuracy: 0.572353910154396
Precision: 0.31097697294880394
Recall: 0.6505319770840641
ROC AUC: 0.5991803077908583
Epoch 42 | Train Loss 0.6715627514890262


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29678 24536]
 [ 6172 11248]]
F1 Score: 0.4228253514773326
Accuracy: 0.5713208811458246
Precision: 0.31433042700648334
Recall: 0.6456946039035592
ROC AUC: 0.596558889364625
Epoch 43 | Train Loss 0.6717711401305029


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29684 24705]
 [ 6166 11079]]
F1 Score: 0.417846838522318
Accuracy: 0.5690454253566742
Precision: 0.3096076458752515
Recall: 0.6424470861119165
ROC AUC: 0.5941096045757508
Epoch 44 | Train Loss 0.6726046882037605


100%|██████████| 1120/1120 [01:32<00:00, 12.13it/s]



 Confusion matrix: 
 [[29728 24625]
 [ 6122 11159]]
F1 Score: 0.4205785357580326
Accuracy: 0.5707764469386045
Precision: 0.3118432819137045
Recall: 0.645738093860309
ROC AUC: 0.5963406124371182
Epoch 45 | Train Loss 0.6730188902999673


  0%|          | 0/1120 [00:00<?, ?it/s]

[[0.47299916]
 [0.47299916]
 [0.47299916]
 [0.47299916]
 [0.47299916]
 [0.47299916]
 [0.47299916]
 [0.47299916]
 [0.47299916]
 [0.47299916]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3834  165]
 [   0    0]]
F1 Score: 0.0
Accuracy: 0.9587396849212303
Precision: 0.0
Recall: 0.0
ROC AUC: notdefined
Epoch 45 | Test Loss 0.6450099396327186


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29823 24763]
 [ 6027 11021]]
F1 Score: 0.4172092671108419
Accuracy: 0.5701761733255158
Precision: 0.30798680974737314
Recall: 0.6464687939934303
ROC AUC: 0.5964088373294011
Epoch 46 | Train Loss 0.6727358302367585


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29838 24552]
 [ 6012 11232]]
F1 Score: 0.42362525458248473
Accuracy: 0.5733310997570986
Precision: 0.31388329979879276
Recall: 0.651356993736952
ROC AUC: 0.5999752425937932
Epoch 47 | Train Loss 0.6708144327891724


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29864 24757]
 [ 5986 11027]]
F1 Score: 0.417713127639828
Accuracy: 0.5708322863444732
Precision: 0.3081544824502571
Recall: 0.648151413624875
ROC AUC: 0.5974504161733061
Epoch 48 | Train Loss 0.6719435320901019


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29793 24664]
 [ 6057 11120]]
F1 Score: 0.41993164781631764
Accuracy: 0.5711394030767513
Precision: 0.31075340934495865
Recall: 0.6473773068638295
ROC AUC: 0.5972347540250433
Epoch 49 | Train Loss 0.6711974661797285


100%|██████████| 1120/1120 [01:30<00:00, 12.33it/s]



 Confusion matrix: 
 [[29781 24715]
 [ 6069 11069]]
F1 Score: 0.41831374475643396
Accuracy: 0.5702599324343189
Precision: 0.30932819137044487
Recall: 0.6458746644882717
ROC AUC: 0.5961775700597552
Epoch 50 | Train Loss 0.6714208945631981
[[0.46711698]
 [0.4702367 ]
 [0.46762004]
 [0.4675526 ]
 [0.46919376]
 [0.46489078]
 [0.47921243]
 [0.46743813]
 [0.468346  ]
 [0.46420503]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3832  164]
 [   2    1]]
F1 Score: 0.011904761904761906
Accuracy: 0.9584896224056014
Precision: 0.006060606060606061
Recall: 0.3333333333333333
ROC AUC: 0.6461461461461462


  0%|          | 0/1120 [00:00<?, ?it/s]

Epoch 50 | Test Loss 0.6386317639123826


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29783 24742]
 [ 6067 11042]]
F1 Score: 0.4175221673945513
Accuracy: 0.5699109361476394
Precision: 0.308573664207467
Recall: 0.6453913145128295
ROC AUC: 0.595808908058799
Epoch 51 | Train Loss 0.6722263347357511


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29720 24773]
 [ 6130 11011]]
F1 Score: 0.4160982522437411
Accuracy: 0.5685987101097244
Precision: 0.3077073552425665
Recall: 0.6423779242751299
ROC AUC: 0.5938845377160795
Epoch 52 | Train Loss 0.6730709143515144


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29708 24547]
 [ 6142 11237]]
F1 Score: 0.4227376182683445
Accuracy: 0.571586118323701
Precision: 0.31402302705119606
Recall: 0.6465849588583923
ROC AUC: 0.5970736977500882
Epoch 53 | Train Loss 0.6715085972100496


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29692 24648]
 [ 6158 11136]]
F1 Score: 0.4196088775010362
Accuracy: 0.5699528157020409
Precision: 0.31120053655264923
Recall: 0.6439227477737944
ROC AUC: 0.5951671155136914
Epoch 54 | Train Loss 0.6719415285225425


100%|██████████| 1120/1120 [01:32<00:00, 12.10it/s]



 Confusion matrix: 
 [[29680 24622]
 [ 6170 11162]]
F1 Score: 0.4202876722644777
Accuracy: 0.5701482536225815
Precision: 0.3119271182651464
Recall: 0.6440110777752135
ROC AUC: 0.5952919740097017
Epoch 55 | Train Loss 0.6724227599267448
[[0.46883318]
 [0.47076368]
 [0.4688458 ]
 [0.46813726]
 [0.48835313]
 [0.4654169 ]
 [0.46462268]
 [0.4691986 ]
 [0.46796304]
 [0.46868116]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 1 0 0 1 0 0]

 Confusion matrix: 
 [[3831  164]
 [   3    1]]
F1 Score: 0.01183431952662722
Accuracy: 0.9582395598899724
Precision: 0.006060606060606061
Recall: 0.25
ROC AUC: 0.6044743429286609


  0%|          | 2/1120 [00:00<01:38, 11.30it/s]

Epoch 55 | Test Loss 0.6396699500462365


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29752 24718]
 [ 6098 11066]]
F1 Score: 0.4179950139759765
Accuracy: 0.5698132171873691
Precision: 0.3092443550190029
Recall: 0.6447215101374971
ROC AUC: 0.5954652162400356
Epoch 56 | Train Loss 0.6721919612692935


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29696 24583]
 [ 6154 11201]]
F1 Score: 0.4215736088372006
Accuracy: 0.5709160454532763
Precision: 0.31301699083389223
Recall: 0.6454047824834341
ROC AUC: 0.5962520144845919
Epoch 57 | Train Loss 0.6716961771249771


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29817 24727]
 [ 6033 11057]]
F1 Score: 0.41823958845557363
Accuracy: 0.5705949688695312
Precision: 0.30899284596467697
Recall: 0.6469865418373317
ROC AUC: 0.5968230597130337
Epoch 58 | Train Loss 0.6716554356472832


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29788 24652]
 [ 6062 11132]]
F1 Score: 0.42024991505908116
Accuracy: 0.5712371220370215
Precision: 0.31108875475072656
Recall: 0.6474351517971385
ROC AUC: 0.5973031747229631
Epoch 59 | Train Loss 0.6717421378408159


100%|██████████| 1120/1120 [01:33<00:00, 11.94it/s]



 Confusion matrix: 
 [[29719 24759]
 [ 6131 11025]]
F1 Score: 0.4165092557612391
Accuracy: 0.5687801881787978
Precision: 0.30809859154929575
Recall: 0.6426323152249942
ROC AUC: 0.5940776393115316
Epoch 60 | Train Loss 0.6727069887199573
[[0.4692435 ]
 [0.4768463 ]
 [0.4677768 ]
 [0.46837136]
 [0.4717556 ]
 [0.47078717]
 [0.4698961 ]
 [0.46848604]
 [0.4680609 ]
 [0.46899763]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3832  164]
 [   2    1]]
F1 Score: 0.011904761904761906
Accuracy: 0.9584896224056014
Precision: 0.006060606060606061
Recall: 0.3333333333333333
ROC AUC: 0.6461461461461462


  0%|          | 0/1120 [00:00<?, ?it/s]

Epoch 60 | Test Loss 0.6383652393780057


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29716 24688]
 [ 6134 11096]]
F1 Score: 0.4186064058550572
Accuracy: 0.569729458078566
Precision: 0.3100827185334228
Recall: 0.6439930354033663
ROC AUC: 0.595101436457657
Epoch 61 | Train Loss 0.6722584141152246


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29839 24669]
 [ 6011 11115]]
F1 Score: 0.4201474201474202
Accuracy: 0.5717117569869057
Precision: 0.31061368209255535
Recall: 0.6490131963097046
ROC AUC: 0.5982187138076005
Epoch 62 | Train Loss 0.6723119962428298


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29819 24848]
 [ 6031 10936]]
F1 Score: 0.4146272108585619
Accuracy: 0.5689337465449368
Precision: 0.3056114464565169
Recall: 0.6445452938056226
ROC AUC: 0.5950057399937071
Epoch 63 | Train Loss 0.6723374557814428


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29719 24741]
 [ 6131 11043]]
F1 Score: 0.41704747158125305
Accuracy: 0.569031465505207
Precision: 0.3086016096579477
Recall: 0.6430068708512868
ROC AUC: 0.594355069652599
Epoch 64 | Train Loss 0.6724436535899129


100%|██████████| 1120/1120 [01:33<00:00, 11.98it/s]



 Confusion matrix: 
 [[29833 24781]
 [ 6017 11003]]
F1 Score: 0.4167487311567305
Accuracy: 0.5700644945137784
Precision: 0.3074837916387212
Recall: 0.6464747356051704
ROC AUC: 0.5963633062066575
Epoch 65 | Train Loss 0.6711700300020831
[[0.4730029]
 [0.4730029]
 [0.4730029]
 [0.4730029]
 [0.4730029]
 [0.4730029]
 [0.4730029]
 [0.4730029]
 [0.4730029]
 [0.4730029]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 1 0 0]

 Confusion matrix: 
 [[3833  164]
 [   1    1]]
F1 Score: 0.011976047904191616
Accuracy: 0.9587396849212303
Precision: 0.006060606060606061
Recall: 0.5
ROC AUC: 0.7294846134600952


  0%|          | 2/1120 [00:00<01:35, 11.72it/s]

Epoch 65 | Test Loss 0.6447942682674953


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29751 24758]
 [ 6099 11026]]
F1 Score: 0.41679109414277343
Accuracy: 0.5692408632772147
Precision: 0.30812653699977643
Recall: 0.6438540145985402
ROC AUC: 0.5948268953911449
Epoch 66 | Train Loss 0.672918720596603


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29768 24630]
 [ 6082 11154]]
F1 Score: 0.4207468879668049
Accuracy: 0.5712650417399558
Precision: 0.3117035546613011
Recall: 0.647133905778603
ROC AUC: 0.5971799533672603
Epoch 67 | Train Loss 0.6717709654676063


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29788 24752]
 [ 6062 11032]]
F1 Score: 0.4172623775483188
Accuracy: 0.5698411368903035
Precision: 0.3082942097026604
Recall: 0.6453726453726454
ROC AUC: 0.5957702977504957
Epoch 68 | Train Loss 0.6726494747613158


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29757 24765]
 [ 6093 11019]]
F1 Score: 0.4166288566243194
Accuracy: 0.5692269034257476
Precision: 0.3079309188464118
Recall: 0.6439340813464236
ROC AUC: 0.5948568833055436
Epoch 69 | Train Loss 0.6723446350012506


100%|██████████| 1120/1120 [01:31<00:00, 12.20it/s]



 Confusion matrix: 
 [[29745 24702]
 [ 6105 11082]]
F1 Score: 0.41841762473806426
Accuracy: 0.5699388558505738
Precision: 0.3096914822266935
Recall: 0.6447896666084831
ROC AUC: 0.5955503790643386
Epoch 70 | Train Loss 0.6716119229793549
[[0.4664925 ]
 [0.46831483]
 [0.47739536]
 [0.48047385]
 [0.46858987]
 [0.46867093]
 [0.46858412]
 [0.47149888]
 [0.46854648]
 [0.46536493]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3832  164]
 [   2    1]]
F1 Score: 0.011904761904761906
Accuracy: 0.9584896224056014
Precision: 0.006060606060606061
Recall: 0.3333333333333333
ROC AUC: 0.6461461461461462


  0%|          | 2/1120 [00:00<01:32, 12.11it/s]

Epoch 70 | Test Loss 0.6393512799626305


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29826 24730]
 [ 6024 11054]]
F1 Score: 0.41822102833793656
Accuracy: 0.5706787279783343
Precision: 0.308909009613235
Recall: 0.6472654877620331
ROC AUC: 0.5969848957983125
Epoch 71 | Train Loss 0.6718405913561583


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29807 24810]
 [ 6043 10974]]
F1 Score: 0.4156739455692127
Accuracy: 0.5692967026830834
Precision: 0.306673373574782
Recall: 0.6448845272374684
ROC AUC: 0.5953151786451911
Epoch 72 | Train Loss 0.6731878070426839


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29809 24605]
 [ 6041 11179]]
F1 Score: 0.4218172213417855
Accuracy: 0.5721863919367898
Precision: 0.31240219092331767
Recall: 0.6491869918699187
ROC AUC: 0.5985027839858286
Epoch 73 | Train Loss 0.671311376776014


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29789 24592]
 [ 6061 11192]]
F1 Score: 0.4220449874615835
Accuracy: 0.5720886729765196
Precision: 0.3127654817795663
Recall: 0.6486987770242856
ROC AUC: 0.5982410050693963
Epoch 74 | Train Loss 0.6711395883666618


100%|██████████| 1120/1120 [01:32<00:00, 12.17it/s]



 Confusion matrix: 
 [[29746 24673]
 [ 6104 11111]]
F1 Score: 0.41929093001754747
Accuracy: 0.5703576513945892
Precision: 0.3105019002906327
Recall: 0.6454255010165554
ROC AUC: 0.5960180299143674
Epoch 75 | Train Loss 0.67244447751769
[[0.46866283]
 [0.4674811 ]
 [0.45762977]
 [0.47111365]
 [0.47044942]
 [0.4873604 ]
 [0.46787962]
 [0.46830308]
 [0.46788782]
 [0.4675998 ]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 1 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3832  164]
 [   2    1]]
F1 Score: 0.011904761904761906
Accuracy: 0.9584896224056014
Precision: 0.006060606060606061
Recall: 0.3333333333333333
ROC AUC: 0.6461461461461462


  0%|          | 0/1120 [00:00<?, ?it/s]

Epoch 75 | Test Loss 0.6383512616157532


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29753 24691]
 [ 6097 11093]]
F1 Score: 0.41880922716804475
Accuracy: 0.5702040930284502
Precision: 0.3099988821819808
Recall: 0.6453170447934846
ROC AUC: 0.5959025896952509
Epoch 76 | Train Loss 0.672192502447537


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29798 24681]
 [ 6052 11103]]
F1 Score: 0.419463911294131
Accuracy: 0.5709718848591451
Precision: 0.3102783366867874
Recall: 0.6472165549402507
ROC AUC: 0.5970898024614064
Epoch 77 | Train Loss 0.6717768555240972


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29810 24600]
 [ 6040 11184]]
F1 Score: 0.4219740416540899
Accuracy: 0.5722701510455929
Precision: 0.31254191817572097
Recall: 0.6493265211333024
ROC AUC: 0.5986018747919775
Epoch 78 | Train Loss 0.6711756942527635


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29737 24739]
 [ 6113 11045]]
F1 Score: 0.4172490650145442
Accuracy: 0.5693106625345506
Precision: 0.308657500558909
Recall: 0.6437230446438978
ROC AUC: 0.5947982283943478
Epoch 79 | Train Loss 0.6719129757157394


100%|██████████| 1120/1120 [01:32<00:00, 12.07it/s]



 Confusion matrix: 
 [[29891 24789]
 [ 5959 10995]]
F1 Score: 0.4169668929424703
Accuracy: 0.5707624870871374
Precision: 0.3072602280348759
Recall: 0.6485195234163029
ROC AUC: 0.5975863893599438
Epoch 80 | Train Loss 0.6717008717890297
[[0.47092322]
 [0.47061676]
 [0.45839447]
 [0.46664104]
 [0.46110204]
 [0.47224516]
 [0.4703764 ]
 [0.46870294]
 [0.4710696 ]
 [0.4699362 ]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3832  164]
 [   2    1]]
F1 Score: 0.011904761904761906
Accuracy: 0.9584896224056014
Precision: 0.006060606060606061
Recall: 0.3333333333333333
ROC AUC: 0.6461461461461462


  0%|          | 2/1120 [00:00<01:35, 11.65it/s]

Epoch 80 | Test Loss 0.640579000351921


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29651 24624]
 [ 6199 11160]]
F1 Score: 0.4199988709707769
Accuracy: 0.5697154982270989
Precision: 0.3118712273641851
Recall: 0.6428941759317933
ROC AUC: 0.594602315971424
Epoch 81 | Train Loss 0.6716552119169916


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29792 24579]
 [ 6058 11205]]
F1 Score: 0.4224555582785077
Accuracy: 0.5723120305999945
Precision: 0.3131287726358149
Recall: 0.6490760586224874
ROC AUC: 0.5985076086825997
Epoch 82 | Train Loss 0.6715312319674662


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29733 24731]
 [ 6117 11053]]
F1 Score: 0.41745666049779057
Accuracy: 0.5693665019404194
Precision: 0.3088810641627543
Recall: 0.643739079790332
ROC AUC: 0.5948296603416995
Epoch 83 | Train Loss 0.6720768520342452


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29697 24548]
 [ 6153 11236]]
F1 Score: 0.4226205028868035
Accuracy: 0.5714186001060949
Precision: 0.31399508160071543
Recall: 0.6461556156190695
ROC AUC: 0.5968081055328273
Epoch 84 | Train Loss 0.6715574799371617


100%|██████████| 1120/1120 [01:31<00:00, 12.22it/s]



 Confusion matrix: 
 [[29747 24669]
 [ 6103 11115]]
F1 Score: 0.41941813516471077
Accuracy: 0.570427450651925
Precision: 0.31061368209255535
Recall: 0.6455453595074921
ROC AUC: 0.5961022151845017
Epoch 85 | Train Loss 0.6728772452367203
[[0.4730029]
 [0.4730029]
 [0.4730029]
 [0.4730029]
 [0.4730029]
 [0.4730029]
 [0.4730029]
 [0.4730029]
 [0.4730029]
 [0.4730029]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3834  165]
 [   0    0]]
F1 Score: 0.0
Accuracy: 0.9587396849212303
Precision: 0.0
Recall: 0.0
ROC AUC: notdefined
Epoch 85 | Test Loss 0.6449800010711427

  0%|          | 2/1120 [00:00<01:31, 12.18it/s]

  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29762 24693]
 [ 6088 11091]]
F1 Score: 0.4188206861393803
Accuracy: 0.5703018119887204
Precision: 0.30994299128101943
Recall: 0.645613830839979
ROC AUC: 0.5960784240050597
Epoch 86 | Train Loss 0.6720119152218104


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29797 24710]
 [ 6053 11074]]
F1 Score: 0.4185897072442403
Accuracy: 0.5705530893151297
Precision: 0.3094679186228482
Recall: 0.6465814211478952
ROC AUC: 0.5966225762058848
Epoch 87 | Train Loss 0.6721031408756971


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29725 24694]
 [ 6125 11090]]
F1 Score: 0.41849846223513654
Accuracy: 0.5697713376329676
Precision: 0.3099150458305388
Recall: 0.6442056346209701
ROC AUC: 0.5952151494003801
Epoch 88 | Train Loss 0.6727408049362046


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29865 24687]
 [ 5985 11097]]
F1 Score: 0.41981613891726255
Accuracy: 0.5718234357986431
Precision: 0.3101106639839034
Recall: 0.6496311907270811
ROC AUC: 0.5985452478052475
Epoch 89 | Train Loss 0.6724838057266814


100%|██████████| 1120/1120 [01:32<00:00, 12.11it/s]



 Confusion matrix: 
 [[29723 24693]
 [ 6127 11091]]
F1 Score: 0.418512508961926
Accuracy: 0.5697573777815004
Precision: 0.30994299128101943
Recall: 0.6441514693924962
ROC AUC: 0.5951847467515259
Epoch 90 | Train Loss 0.6718447069504432
[[0.4730029]
 [0.4730029]
 [0.4730029]
 [0.4730029]
 [0.4730029]
 [0.4730029]
 [0.4730029]
 [0.4730029]
 [0.4730029]
 [0.4730029]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 1 0 0 0]

 Confusion matrix: 
 [[3834  165]
 [   0    0]]
F1 Score: 0.0
Accuracy: 0.9587396849212303
Precision: 0.0
Recall: 0.0
ROC AUC: notdefined


  0%|          | 2/1120 [00:00<01:28, 12.61it/s]

Epoch 90 | Test Loss 0.6449836700681656


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29791 24711]
 [ 6059 11073]]
F1 Score: 0.4185123592108247
Accuracy: 0.5704553703548594
Precision: 0.30943997317236754
Recall: 0.6463343450852206
ROC AUC: 0.5964690697206955
Epoch 91 | Train Loss 0.672232363479478


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29840 24717]
 [ 6010 11067]]
F1 Score: 0.41872079605001794
Accuracy: 0.5710556439679482
Precision: 0.30927230046948356
Recall: 0.6480646483574398
ROC AUC: 0.5975077718756241
Epoch 92 | Train Loss 0.6721652127270188


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29776 24703]
 [ 6074 11081]]
F1 Score: 0.4186327660137139
Accuracy: 0.5703576513945892
Precision: 0.30966353677621283
Recall: 0.6459341299912562
ROC AUC: 0.5962466773233139
Epoch 93 | Train Loss 0.6706595717796258


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29732 24720]
 [ 6118 11064]]
F1 Score: 0.4177774421326889
Accuracy: 0.5695061004550912
Precision: 0.3091884641180416
Recall: 0.6439296938656733
ROC AUC: 0.5949759392710428
Epoch 94 | Train Loss 0.6728225648403168


100%|██████████| 1120/1120 [01:36<00:00, 11.66it/s]



 Confusion matrix: 
 [[29709 24572]
 [ 6141 11212]]
F1 Score: 0.4220035003857952
Accuracy: 0.5712510818884887
Precision: 0.3133243907891795
Recall: 0.6461130640235118
ROC AUC: 0.5967158234765408
Epoch 95 | Train Loss 0.671166334886636
[[0.47221538]
 [0.45551   ]
 [0.47244954]
 [0.4720593 ]
 [0.47242448]
 [0.47209698]
 [0.47034803]
 [0.47219768]
 [0.46652296]
 [0.47155517]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3832  164]
 [   2    1]]
F1 Score: 0.011904761904761906
Accuracy: 0.9584896224056014
Precision: 0.006060606060606061
Recall: 0.3333333333333333
ROC AUC: 0.6461461461461462


  0%|          | 2/1120 [00:00<01:34, 11.81it/s]

Epoch 95 | Test Loss 0.6430887125787281


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29789 24785]
 [ 6061 10999]]
F1 Score: 0.41628188630686547
Accuracy: 0.5693944216433537
Precision: 0.3073720098367986
Recall: 0.6447245017584994
ROC AUC: 0.5952852545073509
Epoch 96 | Train Loss 0.6727778106395688


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29835 24677]
 [ 6015 11107]]
F1 Score: 0.4198767625600121
Accuracy: 0.5715442387692995
Precision: 0.31039011848871007
Recall: 0.6486975820581707
ROC AUC: 0.5980041329721437
Epoch 97 | Train Loss 0.670932446579848


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29712 24576]
 [ 6138 11208]]
F1 Score: 0.42190852625635233
Accuracy: 0.5712371220370215
Precision: 0.3132126089872569
Recall: 0.6461432030439295
ROC AUC: 0.596723237242566
Epoch 98 | Train Loss 0.671781902228083


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29745 24665]
 [ 6105 11119]]
F1 Score: 0.41952158164805314
Accuracy: 0.5704553703548594
Precision: 0.31072546389447797
Recall: 0.645552717138876
ROC AUC: 0.5961176561250344
Epoch 99 | Train Loss 0.671690803819469


100%|██████████| 1120/1120 [01:31<00:00, 12.24it/s]



 Confusion matrix: 
 [[29752 24778]
 [ 6098 11006]]
F1 Score: 0.4162002722734836
Accuracy: 0.5689756260993383
Precision: 0.3075676279901632
Recall: 0.6434752104770813
ROC AUC: 0.5945415663608586
Epoch 100 | Train Loss 0.6728384723620755
[[0.46511132]
 [0.46845356]
 [0.46503562]
 [0.4688239 ]
 [0.48605537]
 [0.4781392 ]
 [0.46852157]
 [0.46834806]
 [0.46577978]
 [0.4685879 ]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 1 0 0 0 0 0]

 Confusion matrix: 
 [[3832  164]
 [   2    1]]
F1 Score: 0.011904761904761906
Accuracy: 0.9584896224056014
Precision: 0.006060606060606061
Recall: 0.3333333333333333
ROC AUC: 0.6461461461461462


  0%|          | 2/1120 [00:00<01:35, 11.71it/s]

Epoch 100 | Test Loss 0.6393300152960277


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29768 24592]
 [ 6082 11192]]
F1 Score: 0.4218779448904972
Accuracy: 0.5717955160957088
Precision: 0.3127654817795663
Recall: 0.6479101539886535
ROC AUC: 0.5977593448383296
Epoch 101 | Train Loss 0.6712437994245972


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29844 24752]
 [ 6006 11032]]
F1 Score: 0.41770474423535653
Accuracy: 0.5706228885724656
Precision: 0.3082942097026604
Recall: 0.647493837304848
ROC AUC: 0.597063645152534
Epoch 102 | Train Loss 0.6721363122974123


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29761 24695]
 [ 6089 11089]]
F1 Score: 0.4187530682376043
Accuracy: 0.5702599324343189
Precision: 0.3098871003800581
Recall: 0.6455349866107812
ROC AUC: 0.5960248019582479
Epoch 103 | Train Loss 0.6712553632046495


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29822 24716]
 [ 6028 11068]]
F1 Score: 0.41860816944024204
Accuracy: 0.5708183264930061
Precision: 0.30930024591996425
Recall: 0.6474029012634535
ROC AUC: 0.5971071494105599
Epoch 104 | Train Loss 0.672295206412673


100%|██████████| 1120/1120 [01:29<00:00, 12.49it/s]



 Confusion matrix: 
 [[29734 24621]
 [ 6116 11163]]
F1 Score: 0.42074515198914497
Accuracy: 0.5709160454532763
Precision: 0.3119550637156271
Recall: 0.6460443312691707
ROC AUC: 0.5965388614307402
Epoch 105 | Train Loss 0.6720178489706345
[[0.47232637]
 [0.47242388]
 [0.4730029 ]
 [0.47272524]
 [0.4720821 ]
 [0.47286275]
 [0.4664093 ]
 [0.47279784]
 [0.47231537]
 [0.47256413]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3832  164]
 [   2    1]]
F1 Score: 0.011904761904761906
Accuracy: 0.9584896224056014
Precision: 0.006060606060606061
Recall: 0.3333333333333333
ROC AUC: 0.6461461461461462


  0%|          | 2/1120 [00:00<01:27, 12.82it/s]

Epoch 105 | Test Loss 0.6437631675175258


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29663 24636]
 [ 6187 11148]]
F1 Score: 0.4197368173346637
Accuracy: 0.5697154982270989
Precision: 0.3115358819584172
Recall: 0.643092010383617
ROC AUC: 0.5946909986539348
Epoch 106 | Train Loss 0.671237145311066


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29788 24727]
 [ 6062 11057]]
F1 Score: 0.4180103207757594
Accuracy: 0.570190133176983
Precision: 0.30899284596467697
Recall: 0.6458905309889597
ROC AUC: 0.5961544739692115
Epoch 107 | Train Loss 0.6715471131993191


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29771 24734]
 [ 6079 11050]]
F1 Score: 0.41766673596280685
Accuracy: 0.5698550967417707
Precision: 0.3087972278113123
Recall: 0.6451047930410415
ROC AUC: 0.5956557815310703
Epoch 108 | Train Loss 0.6720401390854801


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29859 24692]
 [ 5991 11092]]
F1 Score: 0.41961904401611594
Accuracy: 0.5716698774325041
Precision: 0.3099709367315001
Recall: 0.6493004741555933
ROC AUC: 0.5983299129774134
Epoch 109 | Train Loss 0.6723793891923768


100%|██████████| 1120/1120 [01:28<00:00, 12.61it/s]



 Confusion matrix: 
 [[29827 24718]
 [ 6023 11066]]
F1 Score: 0.4185879371323738
Accuracy: 0.5708602060474076
Precision: 0.3092443550190029
Recall: 0.647551056235005
ROC AUC: 0.5971919732545452
Epoch 110 | Train Loss 0.6716878958046436
[[0.46529716]
 [0.48147604]
 [0.47497028]
 [0.46660277]
 [0.46851462]
 [0.4681147 ]
 [0.47137195]
 [0.46777406]
 [0.46552873]
 [0.46848688]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 1 0 0 0 0 0]

 Confusion matrix: 
 [[3832  164]
 [   2    1]]
F1 Score: 0.011904761904761906
Accuracy: 0.9584896224056014
Precision: 0.006060606060606061
Recall: 0.3333333333333333
ROC AUC: 0.6461461461461462


  0%|          | 2/1120 [00:00<01:33, 11.90it/s]

Epoch 110 | Test Loss 0.6392952657881237


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29731 24722]
 [ 6119 11062]]
F1 Score: 0.41770980836401395
Accuracy: 0.5694642209006896
Precision: 0.30913257321708026
Recall: 0.643850765380362
ROC AUC: 0.594922279096256
Epoch 111 | Train Loss 0.6728803627725158


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29771 24743]
 [ 6079 11041]]
F1 Score: 0.417397550279752
Accuracy: 0.569729458078566
Precision: 0.3085457187569864
Recall: 0.6449182242990654
ROC AUC: 0.5955174091007746
Epoch 112 | Train Loss 0.6717621985822916


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29849 24679]
 [ 6001 11105]]
F1 Score: 0.41992815276989975
Accuracy: 0.5717117569869057
Precision: 0.3103342275877487
Recall: 0.6491874196188472
ROC AUC: 0.5982971282366536
Epoch 113 | Train Loss 0.6712341709860734


  0%|          | 0/1120 [00:00<?, ?it/s]


 Confusion matrix: 
 [[29786 24701]
 [ 6064 11083]]
F1 Score: 0.418771608320266
Accuracy: 0.5705251696121953
Precision: 0.30971942767717414
Recall: 0.6463521315682044
ROC AUC: 0.5965073191105837
Epoch 114 | Train Loss 0.6719097362032959


100%|██████████| 1120/1120 [01:31<00:00, 12.18it/s]



 Confusion matrix: 
 [[29861 24796]
 [ 5989 10988]]
F1 Score: 0.41651977786622696
Accuracy: 0.5702459725828517
Precision: 0.3070646098815113
Recall: 0.6472286034046062
ROC AUC: 0.5967815080985561
Epoch 115 | Train Loss 0.6717602757470948
[[0.468746  ]
 [0.47237578]
 [0.46821952]
 [0.46560407]
 [0.46863523]
 [0.47201824]
 [0.46952334]
 [0.46637827]
 [0.46833622]
 [0.46850258]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]

 Confusion matrix: 
 [[3832  164]
 [   2    1]]
F1 Score: 0.011904761904761906
Accuracy: 0.9584896224056014
Precision: 0.006060606060606061
Recall: 0.3333333333333333
ROC AUC: 0.6461461461461462


  0%|          | 2/1120 [00:00<01:34, 11.78it/s]

Epoch 115 | Test Loss 0.6396421913116698


 35%|███▌      | 396/1120 [00:32<00:58, 12.48it/s]